### Article
Smartengo\Domain\Article\Command\AddArticle:
    collectionOperations:
        post:
            path: /articles
            controller: Smartengo\Infrastructure\ApiPlatform\Action\InitializeCommandAction
            write: false # use custom writer instead
    itemOperations: []
    attributes:
        messenger: true
        write_resource: Smartengo\Domain\Article\Entity\Article
        
Smartengo\Domain\Article\Command\UpdateArticle:
    collectionOperations: []
    itemOperations:
        put:
            path: /articles/{id}
            controller: Smartengo\Infrastructure\ApiPlatform\Action\InitializeCommandAction
            write: false
            read: false # use custom action instead
    attributes:
        messenger: true
        write_resource: Smartengo\Domain\Article\Entity\Article

Smartengo\Domain\Article\Query\GetOneArticle:
    collectionOperations: []
    itemOperations:
        get:
            path: /articles/{id}
            controller: Smartengo\Infrastructure\ApiPlatform\Action\InitializeCommandAction
            read: false
    attributes:
        messenger: true
    properties:
        id:
            identifier: true
            
Smartengo\Domain\Article\Command\DeleteArticle:
    collectionOperations: []
    itemOperations:
        delete:
            path: /articles/{id}
            controller: Smartengo\Infrastructure\ApiPlatform\Action\InitializeCommandAction
            read: false
    attributes:
        messenger: true
    properties:
        id:
            identifier: true
            

Smartengo\Domain\Article\Entity\Article:
    collectionOperations: []
    itemOperations:
        get: ~ # use only for uri converter
        
### Tag

Smartengo\Domain\Article\Command\AddTag:
    collectionOperations:
        post:
            path: /tags
            controller: Smartengo\Infrastructure\ApiPlatform\Action\InitializeCommandAction
            write: false # use custom writer instead
    itemOperations: []
    attributes:
        messenger: true
        write_resource: Smartengo\Domain\Article\Entity\Tag

Smartengo\Domain\Article\Entity\Tag:
    collectionOperations: []
    itemOperations:
        get: ~ # use only for uri converter
