Smartengo\Domain\Article\Command\Article:
    properties:
        name:
            - NotBlank: ~
        reference:
            - NotBlank: ~
        content:
            - NotBlank: ~
              
Smartengo\Domain\Article\Query\GetOneArticle:
    properties:
        id:
            - NotBlank: ~
            - Uuid: ~
