Smartengo\Domain\Core\IdentifierAwareCommand:
    properties:
        id:
            - NotBlank: ~
            - Uuid: ~
                
Smartengo\Domain\Article\Command\Article:
    properties:
        name:
            - NotBlank: ~
        reference:
            - NotBlank: ~
        content:
            - NotBlank: ~
