Smartengo\Domain\Core\IdentifierAwareCommand:
    properties:
        id:
            - NotBlank: ~
            - Uuid: ~
                
Smartengo\Domain\Article\Command\Article:
    properties:
        name:
            - NotBlank: ~
        reference:
            - NotBlank: ~
        content:
            - NotBlank: ~
        tags:
            - All:
                  - Smartengo\Infrastructure\Symfony\Validator\TagExist: ~

Smartengo\Domain\Article\Command\AddTag:
    constraints:
        - Smartengo\Infrastructure\Symfony\Validator\UniqueTag:
    properties:
        title:
            - NotBlank: ~
