api_platform:
    title: Hello API Platform
    version: 1.0.0
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
    # Mercure integration, remove if unwanted
    mercure:
        hub_url: '%env(MERCURE_SUBSCRIBE_URL)%'
    exception_to_status:
        Smartengo\Domain\Core\InvalidCommandException: 400
        Smartengo\Domain\Core\InvalidQueryException: 400
        Smartengo\Domain\Core\NotFoundException: 404
        Smartengo\Domain\Core\UnexpectedResultException: 500
